### ISSUE TITLE
What's new in your jsonviewer

### ISSUE THREAD

**Issue by rahulsrivastava71** [php-sourced/daily-util#1]
Hi ,
i just wanted to ask that you have intoduced decoder encoder and 3 more stuffs but what benefits its giving me on general java utility functions as can use them directly .

**Comment by hemantsonu20** [comment]
Hi,
This is not a library which provides decoder encode functions, but it is a GUI tool which can used to encode/decode in base64 / url.
It has some other tools like json viewer. There are features available to format the json to convert a raw json in human readable format.
One another tool File Compare is also available there to compare two files locally.

**Comment by rahulsrivastava71** [comment]
Thanks for your reply.
